In [12]:
from sklearn import datasets,svm,metrics
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
from skimage import data,color,transform

In [2]:
digits = datasets.load_digits()

In [26]:
images = digits.data
print(type(images))#images are already flattened
print(images.shape)

<class 'numpy.ndarray'>
(1797, 64)


In [35]:
resized_image = np.empty((1797,4096))
for i in range(1797):
    temp = transform.resize(images[i],(4096,))
    resized_images = np.append(resized_image,temp)

In [38]:
print(resized_image)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
